### ISSUE TITLE
How to return Status

### ISSUE THREAD

**Issue by vromero** [jmnarloch/rxjava-spring-boot-starter#4]
It is unclear from the documentation how to return different status. From the test we can understand the need of SingleDeferredResult but it seems quite contrary to the purpose of the project.

On the other hand @ResponseStatus doesn't seems to be horoned and neither the return of a Single<ResponseEntity<Void>> of HttpStatus.NO_CONTENT.

**Comment by jmnarloch** [comment]
Whenever you use, Single<T> it being wrapped around
with SingleDeferredResult, which then is being processed as normal
DeferredResult. So the behavior of Single has all of the characteristics of
DeferredResult, if you need to set the HTTP status or some additional
headers you need to map your response entity body with ResponseEntity as
you do with DeferredResult.

So instead of using Single<T> you need to use Single<ResponseEntity<T>>,
the same does not work with Observable<ResponseEntity<T>>, because  the
later is being aggregated.

2016-04-03 6:53 GMT+02:00 vromero <notifications@github.com>:

**Comment by vromero** [comment]
Oh I see, Thank you!

I got confused by the other implementation (newer) that apparently you contributed to spring cloud. Where is actually the other way around,`ResponseEntity<Single<>>` [see here](https://github.com/spring-cloud/spring-cloud-netflix/commit/bca86191b366b1fcb1cb737a5814097ee0ad5d0d#diff-c7e06c0ca29ae4bdbf90ffe20fc65491]) that does not make sense to me. I raised a ticket [there](https://github.com/spring-cloud/spring-cloud-netflix/issues/946) in regarding of it.

**Comment by jmnarloch** [comment]
Closing issue
